### PR TITLE
Checks the commit history of pull requests in CI.

### PR DESCRIPTION
**Pull request by sebright**
The script runs on Travis and only checks the commit history when the commit is
from a pull request. It fails the build if the pull request contains merge
commits ~~or does not start from the branch that it is being merged into~~. If there
is an unexpected exception, the script does not fail the build.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
I think this is a great thing to have.

**Comment by sebright** [comment]
Thanks.  I just updated the script to use TRAVIS_PULL_REQUEST to detect pull requests, which is simpler.

**Comment by bogdandrutu** [comment]
Please re-sync and fix the conflicts in .travis.yml.

**Comment by sebright** [comment]
Rebased

**Comment by bogdandrutu** [comment]
Can we print a message that everything was successful?

**Comment by sebright** [comment]
I just added the check to "Allowed failures" so that we can try it out before making it fail the build.

> Can we print a message that everything was successful?

It currently prints "Checked pull request history." when it finishes.  Do you think it should print more details?

**Comment by bogdandrutu** [comment]
I would print:
Checked pull request history: SUCCEED (or FAILED)

**Comment by sebright** [comment]
Thanks.  I updated the message.

**Pull request merged**
