### PR TITLE
Add simple configuration file for AppVeyor.

### PR DESCRIPTION
**Pull request by sebright**
There is just one build job for now.

See #153.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Can we make this to run automatically?

**Comment by sebright** [comment]
> Can we make this to run automatically?

Yes.  If no one minds, I'll enable it for the repository and trigger a build for this PR.

**Comment by bogdandrutu** [comment]
I think we should do it. Thanks for doing this.

**Comment by sebright** [comment]
No problem.  I just ran the AppVeyor build.

**Pull request merged**
